"""提示词管理模块"""

from .supervisor import (
    SUPERVISOR_PROMPT,
    CONTENT_PUBLISH_SUPERVISOR_PROMPT,
    AUTO_REPLY_SUPERVISOR_PROMPT,
    SCHEDULED_PUBLISH_SUPERVISOR_PROMPT,
    HOT_TOPIC_TRACKING_SUPERVISOR_PROMPT,
    EXCEPTION_HANDLING_SUPERVISOR_PROMPT,
    COMPETITOR_ANALYSIS_SUPERVISOR_PROMPT,
    MESSAGE_HANDLING_SUPERVISOR_PROMPT,
    PERFORMANCE_ANALYSIS_SUPERVISOR_PROMPT,
)

from .agents import (
    CONTENT_GENERATOR_PROMPT,
    CONTENT_STRATEGY_PROMPT,
    VIDEO_GENERATOR_PROMPT,
    XHS_PUBLISHER_PROMPT,
    XHS_INTERACTION_PROMPT,
    XHS_SEARCH_PROMPT,
    DATA_ANALYZER_PROMPT,
    PERFORMANCE_ANALYZER_PROMPT,
    COMPETITOR_ANALYZER_PROMPT,
    EXCEPTION_HANDLER_PROMPT,
)

__all__ = [
    # Supervisor 提示词
    "SUPERVISOR_PROMPT",
    "CONTENT_PUBLISH_SUPERVISOR_PROMPT",
    "AUTO_REPLY_SUPERVISOR_PROMPT",
    "SCHEDULED_PUBLISH_SUPERVISOR_PROMPT",
    "HOT_TOPIC_TRACKING_SUPERVISOR_PROMPT",
    "EXCEPTION_HANDLING_SUPERVISOR_PROMPT",
    "COMPETITOR_ANALYSIS_SUPERVISOR_PROMPT",
    "MESSAGE_HANDLING_SUPERVISOR_PROMPT",
    "PERFORMANCE_ANALYSIS_SUPERVISOR_PROMPT",
    # Agents 提示词
    "CONTENT_GENERATOR_PROMPT",
    "CONTENT_STRATEGY_PROMPT",
    "VIDEO_GENERATOR_PROMPT",
    "XHS_PUBLISHER_PROMPT",
    "XHS_INTERACTION_PROMPT",
    "XHS_SEARCH_PROMPT",
    "DATA_ANALYZER_PROMPT",
    "PERFORMANCE_ANALYZER_PROMPT",
    "COMPETITOR_ANALYZER_PROMPT",
    "EXCEPTION_HANDLER_PROMPT",
]

