"""Supervisor 提示词"""

from .supervisor_prompts import (
    SUPERVISOR_PROMPT,
    CONTENT_PUBLISH_SUPERVISOR_PROMPT,
    AUTO_REPLY_SUPERVISOR_PROMPT,
    SCHEDULED_PUBLISH_SUPERVISOR_PROMPT,
    HOT_TOPIC_TRACKING_SUPERVISOR_PROMPT,
    EXCEPTION_HANDLING_SUPERVISOR_PROMPT,
    COMPETITOR_ANALYSIS_SUPERVISOR_PROMPT,
    MESSAGE_HANDLING_SUPERVISOR_PROMPT,
    PERFORMANCE_ANALYSIS_SUPERVISOR_PROMPT,
)

__all__ = [
    "SUPERVISOR_PROMPT",
    "CONTENT_PUBLISH_SUPERVISOR_PROMPT",
    "AUTO_REPLY_SUPERVISOR_PROMPT",
    "SCHEDULED_PUBLISH_SUPERVISOR_PROMPT",
    "HOT_TOPIC_TRACKING_SUPERVISOR_PROMPT",
    "EXCEPTION_HANDLING_SUPERVISOR_PROMPT",
    "COMPETITOR_ANALYSIS_SUPERVISOR_PROMPT",
    "MESSAGE_HANDLING_SUPERVISOR_PROMPT",
    "PERFORMANCE_ANALYSIS_SUPERVISOR_PROMPT",
]

